M48
; DRILL file {KiCad (6.0.0-rc1-343-g73b39e836d)} date Thursday, December 09, 2021 at 03:59:43 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-12-09T15:59:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-rc1-343-g73b39e836d)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X4.77Y-4.5541
X5.17Y-4.5541
T0
M30
